nick: grrrit-wm
userName: lolrrit
realName: GRRRit the Terrible
default-channel: "#wikimedia-dev"
blacklist:
    L10n-bot
channels:
    "#mediawiki-i18n": [
        "translatewiki.*",
        "mediawiki/extensions/Translate",
        "mediawiki/extensions/TranslationNotifications",
        "mediawiki/extensions/Babel",
        "mediawiki/extensions/UniversalLanguageSelector",
        "mediawiki/extensions/CLDR"
        ]
    "#mediawiki-parsoid": [
        "mediawiki/extensions/Parsoid"
        ]
    "#mediawiki-visualeditor": [
        "mediawiki/extensions/VisualEditor",
        "mediawiki/extensions/TemplateData"
        ]
    "#pywikipediabot": [
        "pywikipediabot.*",
        "pywikibot.*"
        ]
    "#semantic-mediawiki": [
        "mediawiki/extensions/Semantic.*",
        "mediawiki/extensions/SMW.*",
        "mediawiki/extensions/Ask",
        "mediawiki/extensions/Validator",
        "mediawiki/extensions/Maps",
        "mediawiki/extensions/RDFIO",
        "mediawiki/extensions/SolrStore"
        ]
    "#wikimedia-analytics": [
        "analytics/.*"
        ]
    "#wikimedia-fundraising": [
        "mediawiki/extensions/DonationInterface",
        "mediawiki/extensions/CentralNotice",
        "mediawiki/extensions/ContributionTracking",
        "mediawiki/extensions/ContributionReporting",
        "mediawiki/extensions/DonationEmailUnsubscribe",
        "mediawiki/extensions/FundraiserLandingPage",
        "mediawiki/extensions/FundraiserStatistics",
        "wikimedia/fundraising/.*"
        ]
    "#wikimedia-labs": [
        "labs/.*"
        ]
    "#wikimedia-mobile": [
        "mediawiki/extensions/MobileFrontend",
        "mediawiki/extensions/ZeroRatedMobileAccess",
        "apps/android.*"
        ]
    "#wikimedia-operations": [
        "operations.*"
        ]
    "#wikimedia-wikidata": [
        "mediawiki/extensions/Wikibase.*",
        "mediawiki/extensions/Wikidata.*",
        "mediawiki/extensions/Diff",
        "mediawiki/extensions/Ask",
        "mediawiki/extensions/Serialization",
        "mediawiki/extensions/DataTypes",
        "mediawiki/extensions/DataValues",
        "mediawiki/extensions/ValueView",
        "mediawiki/extensions/CommonDataValues",
        "mediawiki/extensions/DataValuesInterfaces"
        ]
